analysis_set:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm
    - speed1
    - gatza

ids:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm
    - mutation
    - speed1
    - gatza

names:
    - Perturbation-response genes
    - Gene Ontology (GSVA)
    - Reactome (GSVA)
    - Signaling Pathway Impact Analysis
    - Pathifier
    - PARADIGM
    - Mutations
    - SPEED
    - Gatza et al. (2009)

short:
    - PROGENy
    - Gene Ontology
    - Reactome
    - SPIA
    - Pathifier
    - PARADIGM
    - Mutations
    - SPEED
    - Gatza (2009)
