analysis_set:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm
    - gsea_speed2016
    - gsva_gatza

ids:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm
    - mutation
    - gsva_speed1
    - gsea_speed2016
    - gsva_gatza
    - gsva
    - zscore
    - speed_original
    - speed_webserver
    - epsa

names:
    - Perturbation-response genes
    - Gene Ontology (GSVA)
    - Reactome (GSVA)
    - Signaling Pathway Impact Analysis
    - Pathifier
    - PARADIGM
    - Mutations
    - SPEED (Parikh et al. 2010)
    - SPEED derivative (Iorio et al. 2016)
    - Gatza et al. (2009)
    - Signatures (top 100 genes GSVA)
    - Signatures (top 100 genes Z-score)
    - SPEED (using our experiments)
    - SPEED (using web server)
    - EPSA (using our experiments)

short:
    - PROGENy
    - Gene Ontology
    - Reactome
    - SPIA
    - Pathifier
    - PARADIGM
    - Mutations
    - SPEED (2010)
    - Iorio (2016)
    - Gatza (2009)
    - GSVA
    - Z-score
    - SPEED (our data)
    - SPEED (web)
    - EPSA (our data)
