tissues:
 - ACC
 - BLCA
 - BRCA
 - CESC
 - CHOL
# - COADREAD # includes all COAD and additional READ
 - COAD # all in COADREAD, but barcode mapping will return COAD or READ
 - DLBC
 - ESCA
# - GBMLGG exclude: merge between GBM and LGG
 - GBM
 - HNSC
 - KICH
# - KIPAN exclude: merge of different kidney cancers
 - KIRC
 - KIRP
 - LAML
 - LGG
 - LIHC
 - LUAD
 - LUSC
 - MESO
 - OV
 - PAAD
 - PCPG
 - PRAD
 - READ # all in COADREAD
 - SARC
 - STAD
# - STES exclude: not in code tables at https://tcga-data.nci.nih.gov/datareports/codeTablesReport.htm
 - TGCT
 - THCA
 - THYM
 - UCEC
 - UCS
 - UVM

# these are tisses that have normals in the tcga
tissues_with_normals:
 - BLCA
 - BRCA
 - CESC
 - COAD # all in COADREAD, but only those have normals
# - COADREAD no normals
 - ESCA
 - HNSC
 - KIRC
 - LIHC
 - LUAD
 - LUSC
 - PAAD
# - PCPG # 3 normals total
 - PRAD
# - SARC # 2 normals total
 - STAD
 - THCA
# - THYM # 2 normals total
 - UCEC # 11 normals
