tissues:
 - ACC
 - BLCA
 - BRCA
 - CESC
 - CHOL
 - COADREAD # includes all COAD and additional READ
# - COAD
 - DLBC
 - ESCA
# - GBMLGG exclude: merge between GBM and LGG
 - GBM
 - HNSC
 - KICH
# - KIPAN exclude: merge of different kidney cancers
 - KIRC
 - KIRP
 - LAML
 - LGG
 - LIHC
 - LUAD
 - LUSC
 - MESO
 - OV
 - PAAD

# these are tisses that have normals in the tcga
tissues_with_normals:
 - BLCA
 - BRCA
 - CESC
 - COAD
 - COADREAD
 - ESCA
 - HNSC
 - KIRC
 - LIHC
 - LUAD
 - LUSC
 - PAAD
